### ISSUE TITLE
通过button或者a标签的onclick事件调用go方法失效？

### ISSUE THREAD

**Issue by hijiangtao** [Franslee/pageSlider#2]
我新建一个button 或者a标签，其中指明onclick到函数change(2)，通过button或者a标签的onclick事件调用go方法失效？
查看div section的transition信息，貌似当前div块的transition为0？

`function change(argument) {
    pageSlider.go(argument);
}`

**Comment by hijiangtao** [comment]
经过调试，发现是所有的a 中的href或者button 的onclick事件都失效了？

**Comment by hijiangtao** [comment]
经过查看代码，发现是库中代码对触摸事件touchstart、touchmove和touchend的绑定造成link失效，自己开发时需要对自己需要实现效果的元素进行新的触摸事件绑定来实现链接及其他效果。

**Comment by Franslee** [comment]
@hijiangtao 可以试试fastclick.js或zepto.js的tap事件

**Comment by lessfish** [comment]
same issue

本来想找个轻便的插件，而且已经写完了，发现调用 swipeLeft 类似事件都失效。。
